#!/bin/bash

echo "🚀 正在启动 Xcode 并运行终活 App..."
echo ""

# 1. 打开 Xcode 项目
echo "📂 打开项目..."
open -a Xcode /Users/lishimin/Documents/zhonghuo-app

sleep 3

echo ""
echo "✅ Xcode 已打开！"
echo ""
echo "======================================"
echo "📋 接下来请手动操作："
echo "======================================"
echo ""
echo "1️⃣ 在 Xcode 顶部，找到模拟器选择器"
echo "   应该显示：iPhone 17 Pro"
echo ""
echo "2️⃣ 点击左上角的 ▶️ 运行按钮"
echo "   或按键盘：Cmd + R"
echo ""
echo "3️⃣ 等待 App 启动（约 10-20 秒）"
echo ""
echo "4️⃣ 看 Xcode 底部窗口"
echo "   黑色背景，显示白色文字"
echo "   这就是控制台！"
echo ""
echo "5️⃣ 如果看不到底部窗口"
echo "   按键盘：Cmd + Shift + Y"
echo ""
echo "======================================"
echo ""
echo "📋 应该看到的日志："
echo "======================================"
echo ""
echo "🟢 ====== ContentView onAppear ======"
echo "   userManager.isLoggedIn: true"
echo "   currentUser: xxx"
echo "⏰ 延迟执行自动签到..."
echo "🔵 autoCheckIn() 被调用"
echo "✅ 自动签到成功！"
echo ""
echo "======================================"
echo ""
echo "💡 提示："
echo "- 底部窗口可以上下拖动调整大小"
echo "- 日志会持续滚动显示"
echo "- 可以复制粘贴日志"
echo ""
echo "现在请操作并告诉我看到了什么！"
